spring.datasource.url=jdbc:mysql://localhost:3306/servicasa?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Hiba11111
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


jwt.secret:NDBiRDI1NDY4MjU0Njg2NTY4NjU2ODY1Njg2NTY4NjU2ODY1Njg2NQ==
jwt.expiration: 8640000
server.port=8081
