ALTER TABLE users
    MODIFY COLUMN role ENUM('CLIENT', 'ARTISAN', 'ADMIN') NOT NULL DEFAULT 'CLIENT';

ALTER TABLE disponibilites
    MODIFY COLUMN jour ENUM('LUNDI', 'MARDI', 'MERCREDI', 'JEUDI', 'VENDREDI', 'SAMEDI', 'DIMANCHE') DEFAULT 'LUNDI';

ALTER TABLE reservations
    MODIFY COLUMN statut_reservation ENUM('EN_ATTENTE', 'ACCEPTEE', 'REFUSEE', 'EN_COURS', 'TERMINEE', 'ANNULEE') DEFAULT 'EN_ATTENTE';

ALTER TABLE paiements
    MODIFY COLUMN statut_paiement ENUM('EN_ATTENTE', 'PAYE', 'ECHOUE', 'REMBOURSE') NOT NULL DEFAULT 'EN_ATTENTE';