  name: ServiCasa

  on:
    push:
      branches: ["main"]
    pull_request:
      branches: ["main"]

  jobs:
    build-test:
      runs-on: ubuntu-latest

      services:
        mysql:
          image: mysql:8.0
          env:
            MYSQL_DATABASE: servicasa_db
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          ports:
            - 3306:3306
          options: >-
            --health-cmd="mysqladmin ping"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Java
          uses: actions/setup-java@v5
          with:
            distribution: "temurin"
            java-version: "21"
            cache: "maven"

        - name: Grant execute permission for mvnw
          run: chmod +x ./mvnw

        - name: Build and Test with Maven
          env:
            SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/servicasa_db
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: ""
            SPRING_FLYWAY_ENABLED: "true"
            SPRING_JPA_HIBERNATE_DDL_AUTO: validate
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
          run: ./mvnw clean package

        - name: Upload Build Artifact
          uses: actions/upload-artifact@v4
          with:
            name: ServiCasa-API
            path: target/*.jar
